---
- name: NOMAD | Ensure data paths
  file:
    dest: "{{ item }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    state: directory
  with_items: "{{ nomad_data_paths }}"

- name: NOMAD | Base config
  template:
    src: "{{ nomad_base_config_template_path }}"
    dest: "{{ nomad_config_dir }}/nomad.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  notify: restart nomad

- name: NOMAD| Server config
  template:
    src: "{{ nomad_server_template_path }}"
    dest: "{{ nomad_config_dir}}/server.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  when: nomad_server_template_path is defined
  notify: restart nomad

- name: NOMAD| Client config
  template:
    src: "{{ nomad_client_template_path }}"
    dest: "{{ nomad_config_dir }}/client.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  when: nomad_client_template_path is defined
  notify: restart nomad
