---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: nomad
    groups:
      - nomad_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: true
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 4646/tcp
    published_ports:
      - 0.0.0.0:4646:4646/tcp
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
verifier:
  name: ansible
